Repository ISISComputingGroup/EPICS-hlx503, pull requests merged in 2022-05, with the labels that each got.

#3 Ticket6240 3he fridge cryo logic
  .gitignore
  configure/RELEASE
  hlx503Sup/Makefile
  hlx503Sup/hlx503.db
  hlx503Sup/hlx503.dbd
  hlx503Sup/hlx503.st
  hlx503Sup/hlx503_recondense.db
  hlx503Sup/seqPVmacros.h
Labels: size/XL

#5 power off the heater ONLY if the control channel is different - other…
  hlx503Sup/hlx503.db
Labels: size/S

#6 Field test fixes
  hlx503Sup/hlx503.db
  hlx503Sup/hlx503.st
Labels: size/L
